### PR TITLE
Fix superclass mismatch for class StringIO

### PR DESCRIPTION
**Pull request by kou**
% ruby -I lib -r ffi_yajl/ffi -r stringio -e ''
    /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': superclass mismatch for class StringIO (TypeError)
            from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'

### CODE REVIEW

**Comment by lamont-granquist** [comment]
don't you need a `class StringIO < Data` later along with the corresponding patch to the c extension?

**Comment by kou** [comment]
> don't you need a class `StringIO < Data` later along with the corresponding patch to the c extension?

It's not needed. We don't need to specify parent class when we open defined class:

```ruby
require "stringio"

class StringIO
end

p StringIO.ancestors # => [StringIO, IO::generic_writable, IO::generic_readable, Enumerable, Data, Object, Kernel, BasicObject]
```

**Comment by kou** [comment]
FYI: It's a good manner that we use `require "date"` instead of `class DateTime < Date`.

**Comment by lamont-granquist** [comment]
ah, cool, you want to fix that one as well and rebase?

**Comment by kou** [comment]
> ah, cool, you want to fix that one as well and rebase?

Done.

**Comment by lamont-granquist** [comment]
Cool, I think it may need to be moved up a level and also fixed in the c-extension, but can shave that yak another day.

**Pull request merged**
