### PR TITLE
emit token that failed utf-8 validation

### PR DESCRIPTION
**Pull request by lamont-granquist**
plus code cleanup of the c-extension

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core @chef/client-engineers need some review.

This will help with UTF-8 issues like chef/ohai#523

The only visible change is the token that failed UTF-8 validation is spit out in the exception.  I also went a little crazy doing some cleanup on the C extension side.

**Comment by lamont-granquist** [comment]
Also now dropping support for 1.8.7.  Doing UTF-8 encoding things with 1.8.7 backcompat is the bridge too far.

**Comment by danielsdeleo** [comment]
Looks like a solid improvement, :+1: though I'm unlikely to catch subtle C issues.

**Comment by lamont-granquist** [comment]
It should be tested well enough, I periodically wrote bad C but which compiled and then the tests blew up and yelled at me appropriately...  I even tried to gratuitously change the rendering of NilClass in keys from "" to "null" because "" in a key made me barf, but a test blew up and yelled at me, so I decided not to worry about that...

**Pull request merged**
