### PR TITLE
Lcg/add appveyor config

### PR DESCRIPTION
**Pull request by lamont-granquist**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core @chef/client-engineers this one is ready.

**Comment by danielsdeleo** [comment]
How hard would it be to add a guard to prevent the buggy behavior from getting used, e.g., parsing big floats on windows raises an error instead of going to lala land?

**Comment by danielsdeleo** [comment]
LGTM other than the one question and appveyor likes it so :+1:

**Comment by lamont-granquist** [comment]
Yeah, I'm not sure how much time I want to spend on it.  That test was plagiarized from yajl-ruby tests and not something we've ever hit in our usage of it.

**Comment by danielsdeleo** [comment]
Yeah if it's a huge PITA involving mucking in the yajl code or whatever, then no big deal. Just wondering if there's a simple fix to make the UX slightly better than program goes into infinite loop.

**Comment by lamont-granquist** [comment]
so @danielsdeleo this looks like a perf problem.

16 digits takes 2 min 22 sec
32 digits takes 2 min 31 sec (9 sec longer)
64 digits takes 3 min 1 sec (39 sec longer)

the spec test has 8 million digits in the floating point number it is trying to parse (and if it takes 4 times longer for every doubling of digits that would be 544 years?  just eyeballing what the geometric progression might be there...)

i'm guessing this is a perf issue in ruby on windows or in the windows floating point libs itself...

**Comment by danielsdeleo** [comment]
Wow. Carry on then.

**Pull request merged**
